#pragma once

//********************************************************************************************
//*
//*    This file is part of Egoboo.
//*
//*    Egoboo is free software: you can redistribute it and/or modify it
//*    under the terms of the GNU General Public License as published by
//*    the Free Software Foundation, either version 3 of the License, or
//*    (at your option) any later version.
//*
//*    Egoboo is distributed in the hope that it will be useful, but
//*    WITHOUT ANY WARRANTY; without even the implied warranty of
//*    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//*    General Public License for more details.
//*
//*    You should have received a copy of the GNU General Public License
//*    along with Egoboo.  If not, see <http://www.gnu.org/licenses/>.
//*
//********************************************************************************************

/// @file script_functions.h
/// @details functions called by scr_run_function()

#include "egoboo_typedef.h"

//--------------------------------------------------------------------------------------------
//--------------------------------------------------------------------------------------------

struct ego_script_state;
struct ego_ai_state;
struct s_ai_state_bundle;
struct ego_chr;

//--------------------------------------------------------------------------------------------
// helper functions
//--------------------------------------------------------------------------------------------

Uint8  _display_message( const CHR_REF by_reference ichr, const PRO_REF by_reference iprofile, int message, struct ego_script_state * pstate );
bool_t _break_passage( int mesh_fx_or, int become, int frames, int starttile, const PASS_REF by_reference passage, int *ptilex, int *ptiley );
Uint8  _find_grid_in_passage( const int x0, const int y0, const int tiletype, const PASS_REF by_reference passage, int *px1, int *py1 );

Uint8   _append_end_text( struct ego_chr * pchr, const int message, struct ego_script_state * pstate );

//--------------------------------------------------------------------------------------------
//--------------------------------------------------------------------------------------------

Uint8 scr_set_AlertBit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearAlertBit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TestAlertBit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Alert( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearAlert( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TestAlert( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Bit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearBit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TestBit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Bits( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearBits( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TestBits( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Spawned( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TimeOut( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AtWaypoint( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AtLastWaypoint( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Attacked( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Bumped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Ordered( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CalledForHelp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Content( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Killed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetKilled( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearWaypoints( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddWaypoint( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FindPath( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Compass( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TargetArmorPrice( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Time( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_Content( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_JoinTargetTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToNearbyEnemy( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToTargetLeftHand( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToTargetRightHand( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWhoeverAttacked( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWhoeverBumped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWhoeverCalledForHelp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToOldTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TurnModeToVelocity( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TurnModeToWatch( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TurnModeToSpin( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_BumpHeight( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasItemID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHoldingItemID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasSkillID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Else( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Run( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Walk( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Sneak( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DoAction( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_KeepAction( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_IssueOrder( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DropWeapons( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetDoAction( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_OpenPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClosePassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PassageOpen( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GoPoof( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CostTargetItemID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DoActionOverride( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Healed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SendPlayerMessage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CallForHelp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddIDSZ( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_State( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_State( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetCanOpenStuff( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Grabbed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Dropped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWhoeverIsHolding( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DamageTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_XIsLessThanY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_WeatherTime( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_BumpHeight( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Reaffirmed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_UnkeepAction( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsOnOtherTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsOnHatedTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PressLatchButton( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToTargetOfLeader( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_LeaderKilled( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BecomeLeader( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ChangeTargetArmor( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveMoneyToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DropKeys( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_LeaderIsAlive( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsOldTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToLeader( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnCharacter( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_RespawnCharacter( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ChangeTile( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Used( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DropMoney( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_OldTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DetachFromHolder( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasVulnerabilityID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CleanUp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CleanedUp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Sitting( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsHurt( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsAPlayer( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PlaySound( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsAlive( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Stop( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DisaffirmCharacter( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ReaffirmCharacter( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsSelf( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsMale( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsFemale( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToSelf( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToRider( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_AttackTurn( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_DamageType( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BecomeSpell( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BecomeSpellbook( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ScoredAHit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Disaffirmed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TranslateOrder( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWhoeverWasHit( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWideEnemy( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Changed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_InWater( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Bored( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TooMuchBaggage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Confused( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasSpecialID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PressTargetLatchButton( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Invisible( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ArmorIs( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TargetGrogTime( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TargetDazeTime( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_DamageType( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_WaterLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EnchantTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EnchantChild( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TeleportTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveExperienceToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_IncreaseAmmo( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_UnkurseTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveExperienceToTargetTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Unarmed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_RestockTargetAmmoIDAll( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_RestockTargetAmmoIDFirst( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FlashTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_RedShift( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_GreenShift( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_BlueShift( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Light( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Alpha( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HitFromBehind( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HitFromFront( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HitFromLeft( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HitFromRight( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsOnSameTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_KillTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_UndoEnchant( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_WaterLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CostTargetMana( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasAnyID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_BumpSize( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_NotDropped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_YIsLessThanX( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_FlyHeight( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Blocked( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsDefending( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsAttacking( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs0( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs1( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs2( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs3( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs4( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs5( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs6( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs7( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ContentIs( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TurnModeToWatchTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIsNot( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_XIsEqualToY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DebugMessage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BlackTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SendMessageNear( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HitGround( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_NameIsKnown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_UsageIsKnown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HoldingItemID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HoldingRangedWeapon( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HoldingMeleeWeapon( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HoldingShield( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Kursed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsKursed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsDressedUp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_OverWater( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Thrown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeNameKnown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeUsageKnown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StopTargetMovement( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_XY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_XY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddXY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeAmmoKnown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnAttachedParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnExactParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AccelerateTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_distanceIsMoreThanTurn( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Crushed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeCrushValid( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToLowestTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_NotPutAway( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TakenOut( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AmmoOut( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PlaySoundLooped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StopSound( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HealSelf( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Equip( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasItemIDEquipped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_OwnerToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToOwner( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Frame( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BreakPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_ReloadTime( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWideBlahID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PoofTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ChildDoActionOverride( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnPoof( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_SpeedPercent( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_ChildState( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnAttachedSizedParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ChangeArmor( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ShowTimer( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FacingTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PlaySoundVolume( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnAttachedFacedParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIsOdd( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToDistantEnemy( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Teleport( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveStrengthToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveWisdomToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveIntelligenceToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveDexterityToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveLifeToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveManaToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ShowMap( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ShowYouAreHere( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ShowBlipXY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HealTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PumpTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CostAmmo( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeSimilarNamesKnown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnAttachedHolderParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetReloadTime( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_FogLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_FogLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_FogTAD( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_FogBottomLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_FogBottomLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CorrectActionForHand( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsMounted( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SparkleIcon( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_UnsparkleIcon( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TileXY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TileXY( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_ShadowSize( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_OrderTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToWhoeverIsInPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CharacterWasABook( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_EnchantBoostValues( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnCharacterXYZ( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnExactCharacterXYZ( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ChangeTargetClass( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PlayFullSound( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnExactChaseParticle( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_CreateOrder( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_OrderSpecialID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_UnkurseTargetInventory( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsSneaking( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DropItems( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_RespawnTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetDoActionSetFrame( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetCanSeeInvisible( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToNearestBlahID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToNearestEnemy( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToNearestFriend( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToNearestLifeform( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FlashPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FindTileInPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HeldInLeftHand( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_NotAnItem( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_ChildAmmo( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HitVulnerable( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsFlying( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_IdentifyTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BeatModule( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EndModule( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DisableExport( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EnableExport( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TargetState( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Equipped( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DropTargetMoney( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TargetContent( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DropTargetKeys( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_JoinTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetJoinTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearMusicPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ClearEndMessage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddEndMessage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PlayMusic( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_MusicPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeCrushInvalid( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StopMusic( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FlashVariable( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AccelerateUp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FlashVariableHeight( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_DamageTime( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs8( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs9( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs10( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs11( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs12( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs13( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs14( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_StateIs15( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsAMount( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsAPlatform( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddStat( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DisenchantTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DisenchantAll( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_VolumeNearestTeammate( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddShopPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetPayForArmor( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_JoinEvilTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_JoinNullTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_JoinGoodTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PitsKill( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToPassageID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MakeNameUnknown( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnExactParticleEndSpawn( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnPoofSpeedSpacingDamage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveExperienceToGoodTeam( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DoNothing( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GrogTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DazeTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EnableRespawn( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DisableRespawn( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DispelTargetEnchantID( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_HolderBlocked( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasNotFullMana( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EnableListenSkill( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToLastItemUsed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_FollowLink( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_OperatorIsLinux( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsAWeapon( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SomeoneIsStealing( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsASpell( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_Backstabbed( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_get_TargetDamageType( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddQuest( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_BeatQuestAllPlayers( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetHasQuest( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_QuestLevel( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddQuestAllPlayers( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AddBlipAllEnemies( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_PitsFall( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsOwner( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_End( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TakePicture( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Speech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_MoveSpeech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_SecondMoveSpeech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_AttackSpeech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_AssistSpeech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TerrainSpeech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_SelectSpeech( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_OperatorIsMacintosh( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_ModuleHasIDSZ( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_MorphToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveManaFlowToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveManaReturnToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_Money( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetCanSeeKurses( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SpawnAttachedCharacter( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_KurseTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_ChildContent( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToChild( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_DamageThreshold( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_AccelerateTargetUp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetAmmo( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_EnableInvictus( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DisableInvictus( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetDamageSelf( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_SetTargetSize( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_DrawBillboard( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_set_TargetToBlahInPassage( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_TargetIsFacingSelf( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_LevelUp( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
Uint8 scr_GiveSkillToTarget( struct ego_script_state * pstate, struct s_ai_state_bundle * pbdl_self );
