/*******************************************************************************
*  SCRIPT.C                                                                    *
*    - EGOBOO-Game                                                             *
*                                                                              *
*    - All functions to run a script                                           *
*      (c) 2013 The Egoboo Team                                                *
*                                                                              *
*  This program is free software; you can redistribute it and/or modify        *
*  it under the terms of the GNU General Public License as published by        *
*  the Free Software Foundation; either version 2 of the License, or           *
*  (at your option) any later version.                                         *
*                                                                              *
*  This program is distributed in the hope that it will be useful,             *
*  but WITHOUT ANY WARRANTY; without even the implied warranty of              *
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               *
*  GNU Library General Public License for more details.                        *
*                                                                              *
*  You should have received a copy of the GNU General Public License           *
*  along with this program; if not, write to the Free Software                 *
*  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.  *
*******************************************************************************/


/*******************************************************************************
* INCLUDES                                                                     *
*******************************************************************************/

#include "msg.h"        // Type of messages

/*******************************************************************************
* DEFINES                                                                      *
*******************************************************************************/

#define ARG_CHAR ((char)1)
#define ARG_SINT ((char)2)
#define ARG_INT  ((char)3)

/*******************************************************************************
* TYPEDEFS                                                                     *
*******************************************************************************/

// codes less then zero are functions, codes >= 0 are argument values
typedef struct
{
    char num_code;          // Number of codes to set
    char codes[4];
    char *name;             // Name of function
    char args[6+1];         // Arguments, if any    

} SCRIPT_FUNC_T;

// Constants
typedef struct
{
    // Always a prefix 'which' and a value
    char code;
    short int subcode;
    char *name;             // Name of constant
} SCRIPT_CONST_T;

// Arguments for functions
typedef struct
{
    // Always a prefix 'which' and a value
    char code[2];    
    char *name;             // Name of constant
    
} SCRIPT_ARG_T;

// Operators
typedef struct
{
    char code;
    char name[2];
   
} SCRIPT_OP_T;

/*******************************************************************************
* DATA                                                                         *
*******************************************************************************/

// Do more work while encoding to save function calls at decoding time
static SCRIPT_FUNC_T ScrFunc[] = 
{
    { 0, { FUNC_ACCEL }, "acceleratetarget", { 0 } },
    { 0, { FUNC_ACCEL }, "acceleratetargetup", { 0 } },
    { 0, { FUNC_ACCEL }, "accelerateup", { 0 } },
    { 0, { FUNC_ADD }, "addblipallenemies", { 0 } },
    { 0, { FUNC_ADD, SVAR_MSG }, "addendmessage", { 0 } },
    { 0, { FUNC_ADD }, "addidsz", { 0 } },
    { 0, { FUNC_ADD }, "addquestallplayers", { 0 } },
    { 0, { FUNC_ADD, SVAR_PASSAGE }, "addshoppassage", { 0 } },
    { 0, { FUNC_ADD }, "addstat", { 0 } },
    { 0, { FUNC_ADD }, "addtargetquest", { 0 } },
    { 0, { FUNC_ADD }, "addwaypoint", { 0 } },
    { 0, { FUNC_ADD }, "addxy", { 0 } },
    { 0, { FUNC_MODULE }, "beatmodule", { 0 } },
    { 0, { 0 }, "beatquestallplayers", { 0 } },
    { 0, { FUNC_TEAM }, "becomeleader", { 0 } },
    { 0, { 0 }, "becomespell", { 0 } },
    { 0, { 0 }, "becomespellbook", { 0 } },
    { 0, { 0 }, "blacktarget", { 0 } },
    { 0, { FUNC_PASSAGE, 3 }, "breakpassage", { 0 } },
    { 0, { FUNC_TEAM }, "callforhelp", { 0 } },
    { 0, { 0 }, "changearmor", { 0 } },
    { 0, { 0 }, "changetargetarmor", { 0 } },
    { 0, { 0 }, "changetargetclass", { 0 } },
    { 0, { 0 }, "changetile", { 0 } },
    { 0, { 0 }, "childdoactionoverride", { 0 } },
    { 0, { 0 }, "cleanup", { 0 } },
    { 0, { FUNC_MSG }, "clearendmessage", { 0 } },
    { 0, { FUNC_PASSAGE, 4 }, "clearmusicpassage", { 0 } },
    { 0, { 0 }, "clearwaypoints", { 0 } },
    { 0, { FUNC_PASSAGE, 1 }, "closepassage", { 0 } },
    { 0, { 0 }, "compass", { 0 } },
    { 0, { 0 }, "correctactionforhand", { 0 } },
    { 0, { 0 }, "costammo", { 0 } },
    { 0, { 0 }, "costtargetitemid", { 0 } },
    { 0, { 0 }, "costtargetmana", { 0 } },
    { 0, { FUNC_ORDER }, "createorder", { 0 } },
    { 0, { 0 }, "damagetarget", { 0 } },
    { 0, { 0 }, "dazetarget", { 0 } },
    { 0, { 0 }, "debugmessage", { 0 } },
    { 0, { 0 }, "detachfromholder", { 0 } },
    { 0, { 0 }, "disableexport", { 0 } },
    { 0, { 0 }, "disableinvictus", { 0 } },
    { 0, { 0 }, "disablerespawn", { 0 } },
    { 0, { 0 }, "disaffirmcharacter", { 0 } },
    { 0, { FUNC_SPELL }, "disenchantall", { 0 } },
    { 0, { FUNC_SPELL }, "disenchanttarget", { 0 } },
    { 0, { FUNC_SPELL }, "dispeltargetenchantid", { 0 } },
    { 0, { 0 }, "doaction", { 0 } },
    { 0, { 0 }, "doactionoverride", { 0 } },
    { 0, { FUNC_END }, "donothing", { 0 } },
    { 0, { 0 }, "drawbillboard", { 0 } },
    { 0, { FUNC_DROP }, "dropitems", { 0 } },
    { 0, { FUNC_DROP }, "dropkeys", { 0 } },
    { 0, { FUNC_DROP, SVAR_MONEY }, "dropmoney", { 0 } },
    { 0, { FUNC_DROP, SVAR_TARGET }, "droptargetkeys", { 0 } },
    { 0, { FUNC_DROP, SVAR_TARGET, SVAR_MONEY }, "droptargetmoney", { 0 } },
    { 0, { FUNC_DROP }, "dropweapons", { 0 } },
    { 0, { FUNC_ELSE }, "else", { 0 } },
    { 0, { FUNC_ENABLE }, "enableexport", { 0 } },
    { 0, { FUNC_ENABLE }, "enableinvictus", { 0 } },
    { 0, { FUNC_ENABLE }, "enablelistenskill", { 0 } },
    { 0, { FUNC_ENABLE }, "enablerespawn", { 0 } },
    { 0, { FUNC_SPELL }, "enchantchild", { 0 } },
    { 0, { FUNC_SPELL }, "enchanttarget", { 0 } },
    { 0, { FUNC_END }, "end", { 0 } },
    { 0, { FUNC_MODULE }, "endmodule", { 0 } },
    { 0, { FUNC_MIXED }, "equip", { 0 } },
    { 0, { FUNC_MIXED }, "findpath", { 0 } },
    { 0, { FUNC_PASSAGE, 6 }, "findtileinpassage", { 0 } },
    { 0, { FUNC_PASSAGE, 7 }, "flashpassage", { 0 } },
    { 0, { FUNC_TARGET }, "flashtarget", { 0 } },
    { 0, { FUNC_MIXED }, "flashvariable", { 0 } },
    { 0, { FUNC_MIXED }, "flashvariableheight", { 0 } },
    { 0, { FUNC_MIXED }, "followlink", { 0 } },
    { 0, { FUNC_GET }, "getattackturn", { 0 } },
    { 0, { FUNC_GET }, "getbumpheight", { 0 } },
    { 0, { FUNC_GET }, "getcontent", { 0 } },
    { 0, { FUNC_GET }, "getdamagetype", { 0 } },
    { 0, { FUNC_GET }, "getfogbottomlevel", { 0 } },
    { 0, { FUNC_GET }, "getfoglevel", { 0 } },
    { 0, { FUNC_GET }, "getstate", { 0 } },
    { 0, { FUNC_GET }, "gettargetarmorprice", { 0 } },
    { 0, { FUNC_GET }, "gettargetcontent", { 0 } },
    { 0, { FUNC_GET }, "gettargetdamagetype", { 0 } },
    { 0, { FUNC_GET }, "gettargetdazetime", { 0 } },
    { 0, { FUNC_GET }, "gettargetgrogtime", { 0 } },
    { 0, { FUNC_GET }, "gettargetshieldprofiency", { 0 } },
    { 0, { FUNC_GET }, "gettargetstate", { 0 } },
    { 0, { FUNC_GET }, "gettilexy", { 0 } },
    { 0, { FUNC_GET }, "getwaterlevel", { 0 } },
    { 0, { FUNC_GET }, "getxy", { 0 } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givedexteritytotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE }, "giveexperiencetogoodteam", { VAR_SINT } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "giveexperiencetotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "giveexperiencetotargetteam", { VAR_SINT } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "giveintelligencetotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givelifetotarget", { VAR_SINT } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givemanaflowtotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givemanareturntotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givemanatotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givemoneytotarget", { VAR_SINT } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "giveskilltotarget", { VAR_SINT } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givestrengthtotarget", { VAR_CHAR } },
    { 0, { FUNC_GIVE, SVAL_TARGET }, "givewisdomtotarget", { VAR_CHAR } },
    { 0, { 0 }, "gopoof", { 0 } },
    { 0, { 0 }, "grogtarget", { 0 } },
    { 0, { 0 }, "healself", { 0 } },
    { 0, { 0 }, "healtarget", { 0 } },
    { 0, { 0 }, "identifytarget", { 0 } },
    { 0, { FUNC_IF }, "ifammoout", { 0 } },
    { 0, { FUNC_IF }, "ifarmoris", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_ATLASTWAYPOINT }, "ifatlastwaypoint", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_ATTACKED }, "ifattacked", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_ATWAYPOINT }, "ifatwaypoint", { 0 } },
    { 0, { FUNC_IF }, "ifbackstabbed", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_BLOCKED }, "ifblocked", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_BORED }, "ifbored", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_BUMPED }, "ifbumped", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_CALLEDFORHELP }, "ifcalledforhelp", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_CHANGED }, "ifchanged", { 0 } },
    { 0, { FUNC_IF }, "ifcharacterwasabook", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_CLEANEDUP }, "ifcleanedup", { 0 } },
    { 0, { FUNC_IF }, "ifcontentis", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_CRUSHED }, "ifcrushed", { 0 } },
    { 0, { FUNC_IF }, "ifdazed", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_DISAFFIRMED }, "ifdisaffirmed", { 0 } },
    { 0, { FUNC_IF }, "ifdismounted", { 0 } },
    { 0, { FUNC_IF }, "ifdistanceismorethanturn", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_DROPPED }, "ifdropped", { 0 } },
    { 0, { FUNC_IF }, "ifequipped", { 0 } },
    { 0, { FUNC_IF }, "iffacingtarget", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_GRABBED }, "ifgrabbed", { 0 } },
    { 0, { FUNC_IF }, "ifgrogged", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_HEALED }, "ifhealed", { 0 } },
    { 0, { FUNC_IF }, "ifheld", { 0 } },
    { 0, { FUNC_IF }, "ifheldinlefthand", { 0 } },
    { 0, { FUNC_IF }, "ifhitfrombehind", { 0 } },
    { 0, { FUNC_IF }, "ifhitfromfront", { 0 } },
    { 0, { FUNC_IF }, "ifhitfromleft", { 0 } },
    { 0, { FUNC_IF }, "ifhitfromright", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_HITGROUND }, "ifhitground", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_HITVULNERABLE }, "ifhitvulnerable", { 0 } },
    { 0, { FUNC_IF }, "ifholderblocked", { 0 } },
    { 0, { FUNC_IF }, "ifholdingitemid", { 0 } },
    { 0, { FUNC_IF }, "ifholdingmeleeweapon", { 0 } },
    { 0, { FUNC_IF }, "ifholdingrangedweapon", { 0 } },
    { 0, { FUNC_IF }, "ifholdingshield", { 0 } },
    { 0, { FUNC_IF }, "ifinvisible", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_INWATER }, "ifinwater", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_KILLED }, "ifkilled", { 0 } },
    { 0, { FUNC_IF }, "ifkursed", { 0 } },
    { 0, { FUNC_IF }, "ifleaderisalive", { 0 } },
    { 0, { FUNC_IF }, "ifleaderkilled", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_LEVELUP }, "iflevelup", { 0 } },
    { 0, { FUNC_IF }, "ifmodulehasidsz", { 0 } },
    { 0, { FUNC_IF }, "ifmounted", { 0 } },
    { 0, { FUNC_IF }, "ifnameisknown", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_NOTDROPPED }, "ifnotdropped", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_NOTPUTAWAY }, "ifnotputaway", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_NOTTAKENOUT }, "ifnottakenout", { 0 } },
    { 0, { FUNC_IF }, "ifoperatorislinux", { 0 } },
    { 0, { FUNC_IF }, "ifoperatorismacintosh", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_ORDERED }, "ifordered", { 0 } },
    { 0, { FUNC_IF }, "ifoverwater", { 0 } },
    { 0, { FUNC_IF, SVAR_PASSAGE }, "ifpassageopen", { 0 } },
    { 0, { FUNC_IF, SVAR_ALERT, MSG_PUTAWAY }, "ifputaway", { 0 } },
    { 0, { FUNC_IF, SVAR_ALERT, MSG_REAFFIRMED }, "ifreaffirmed", { 0 } },
    { 0, { FUNC_IF }, "ifscoredahit", { 0 } },
    { 0, { FUNC_IF }, "ifsitting", { 0 } },
    { 0, { FUNC_IF }, "ifsomeoneisstealing", { 0 } },
    { 0, { FUNC_IF, SVAR_ALERT, MSG_SPAWNED }, "ifspawned", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE }, "ifstateis", { ARG_CHAR } },
    { 0, { FUNC_IF, SVAR_STATE, 0 }, "ifstateis0", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 1 }, "ifstateis1", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 10 }, "ifstateis10", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 11 }, "ifstateis11", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 12 }, "ifstateis12", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 13 }, "ifstateis13", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 14 }, "ifstateis14", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 15 }, "ifstateis15", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  2 }, "ifstateis2", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  3 }, "ifstateis3", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  4 }, "ifstateis4", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  5 }, "ifstateis5", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  6 }, "ifstateis6", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  7 }, "ifstateis7", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  8 }, "ifstateis8", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  9 }, "ifstateis9", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  6 }, "ifstateischarge", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  7 }, "ifstateiscombat", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  3 }, "ifstateisfollow", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE,  2 }, "ifstateisguard", { 0 } },
    // @todo: Add argument for proper function
    { 0, { FUNC_IF, SVAR_STATE, FUNC_STATE }, "ifstateisnot", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, FUNC_STATE }, "ifstateisodd", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 0 }, "ifstateisparry", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 5 }, "ifstateisretreat", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 4 }, "ifstateissurround", { 0 } },
    { 0, { FUNC_IF, SVAR_STATE, 1 }, "ifstateiswander", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_TAKENOUT }, "iftakenout", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetcanopenstuff", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetcanseeinvisible", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetcanseekurses", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasanyid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasitemid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasitemidequipped", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasnotfullmana", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasquest", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasskillid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasspecialid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargethasvulnerabilityid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetholdingitemid", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisalive", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisamount", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisaplatform", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisaplayer", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisaspell", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisattacking", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisaweapon", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisdefending", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisdressedup", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisfacingself", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisfemale", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisflying", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetishurt", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetiskursed", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetismale", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetismounted", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisoldtarget", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisonhatedteam", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisonotherteam", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisonsameteam", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisowner", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetisself", { 0 } },
    { 0, { FUNC_IF, SVAR_TARGET }, "iftargetissneaking", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_TARGETKILLED }, "iftargetkilled", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_THROWN }, "ifthrown", { 0 } },
    { 0, { FUNC_IF }, "iftimeout", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_TOOMUCHBAGGAGE }, "iftoomuchbaggage", { 0 } },
    { 0, { FUNC_IF, SVAL_ALERT, MSG_USED }, "ifunarmed", { 0 } },
    { 0, { FUNC_IF }, "ifusageisknown", { 0 } },
    { 0, { FUNC_IF }, "ifused", { 0 } },
    { 0, { FUNC_IF, SVAR_COMPXY }, "ifxisequaltoy", { 0 } },
    { 0, { FUNC_IF, SVAR_COMPXY }, "ifxislessthany", { 0 } },
    { 0, { FUNC_IF, SVAR_COMPXY }, "ifxismorethany", { 0 } },
    { 0, { FUNC_IF, SVAR_COMPXY }, "ifyisequaltox", { 0 } },
    { 0, { FUNC_IF, SVAR_COMPXY }, "ifyislessthanx", { 0 } },
    { 0, { FUNC_IF, SVAR_COMPXY }, "ifyismorethanx", { 0 } },
    { 0, { 0 }, "increaseammo", { 0 } },
    { 0, { FUNC_ORDER }, "issueorder", { 0 } },
    { 0, { FUNC_TEAM }, "joinevilteam", { 0 } },
    { 0, { FUNC_TEAM }, "joingoodteam", { 0 } },
    { 0, { FUNC_TEAM }, "joinnullteam", { 0 } },
    { 0, { FUNC_TEAM }, "jointargetteam", { 0 } },
    { 0, { FUNC_TEAM }, "jointeam", { 0 } },
    { 0, { 0 }, "keepaction", { 0 } },
    { 0, { FUNC_TARGET }, "killtarget", { 0 } },
    { 0, { FUNC_TARGET }, "kursetarget", { 0 } },
    { 0, { 0 }, "makeammoknown", { 0 } },
    { 0, { 0 }, "makecrushinvalid", { 0 } },
    { 0, { 0 }, "makecrushvalid", { 0 } },
    { 0, { 0 }, "makenameknown", { 0 } },
    { 0, { 0 }, "makenameunknown", { 0 } },
    { 0, { 0 }, "makesimilarnamesknown", { 0 } },
    { 0, { 0 }, "makeusageknown", { 0 } },
    { 0, { FUNC_TARGET }, "morphtotarget", { 0 } },
    { 0, { 0 }, "notanitem", { 0 } },
    { 0, { FUNC_PASSAGE, 0 }, "openpassage", { 0 } },
    { 0, { FUNC_ORDER }, "orderspecialid", { 0 } },
    { 0, { FUNC_ORDER }, "ordertarget", { 0 } },
    { 0, { 0 }, "pitsfall", { 0 } },
    { 0, { 0 }, "pitskill", { 0 } },
    { 0, { FUNC_SOUND }, "playfullsound", { 0 } },
    { 0, { FUNC_SOUND }, "playmusic", { 0 } },
    { 0, { FUNC_SOUND }, "playsound", { 0 } },
    { 0, { FUNC_SOUND }, "playsoundlooped", { 0 } },
    { 0, { FUNC_SOUND }, "playsoundvolume", { 0 } },
    { 0, { 0 }, "pooftarget", { 0 } },
    { 0, { 0 }, "presslatchbutton", { 0 } },
    { 0, { 0 }, "presstargetlatchbutton", { 0 } },
    { 0, { 0 }, "pumptarget", { 0 } },
    { 0, { 0 }, "reaffirmcharacter", { 0 } },
    { 0, { 0 }, "respawncharacter", { 0 } },
    { 0, { 0 }, "respawntarget", { 0 } },
    { 0, { 0 }, "restocktargetammoidall", { 0 } },
    { 0, { 0 }, "restocktargetammoidfirst", { 0 } },
    { 0, { 0 }, "run", { 0 } },
    { 0, { FUNC_MSG, 1 }, "sendmessage", { 0 } },
    { 0, { FUNC_MSG, 2 }, "sendmessagenear", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setalpha", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setblueshift", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setbumpheight", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setbumpsize", { 0 } },
    { 0, { FUNC_SET }, "setchildammo", { 0 } },
    { 0, { FUNC_SET }, "setchildcontent", { 0 } },
    { 0, { FUNC_SET }, "setchildstate", { 0 } },
    { 0, { FUNC_SET }, "setcontent", { 0 } },
    { 0, { FUNC_SET }, "setdamagethreshold", { 0 } },
    { 0, { FUNC_SET }, "setdamagetime", { 0 } },
    { 0, { FUNC_SET }, "setdamagetype", { 0 } },
    { 0, { FUNC_SET }, "setenchantboostvalues", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setflyheight", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setfogbottomlevel", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setfoglevel", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setfogtad", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setframe", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setgreenshift", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setlight", { 0 } },
    { 0, { FUNC_SET, SVAR_MONEY }, "setmoney", { 0 } },
    { 0, { FUNC_SET, SVAR_SOUND, SVAR_PASSAGE }, "setmusicpassage", { 0 } },
    { 0, { FUNC_SET }, "setoldtarget", { 0 } },
    { 0, { FUNC_SET }, "setownertotarget", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setredshift", { 0 } },
    { 0, { FUNC_SET }, "setreloadtime", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setshadowsize", { 0 } },
    { 0, { FUNC_SET }, "setspeech", { 0 } },
    { 0, { FUNC_SET, SVAR_DISPLAY }, "setspeedpercent", { 0 } },
    { 0, { FUNC_SET, SVAR_STATE }, "setstate", { VAR_CHAR } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargetammo", { VAR_CHAR } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargetquestlevel", { VAR_CHAR } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargetreloadtime", { VAR_CHAR } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargetsize", { VAR_CHAR } },
    { 0, { FUNC_SET, SVAR_TARGET, FUNC_PASSAGE }, "settargettoblahinpassage", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettochild", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettodistantenemy", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettolastitemused", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettoleader", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettolowesttarget", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettonearbyenemy", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettonearbymeleeweapon", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettonearestblahid", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettonearestenemy", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettonearestfriend", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettonearestlifeform", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettooldtarget", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettoowner", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET, FUNC_PASSAGE }, "settargettopassageid", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettorider", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettoself", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettotargetlefthand", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettotargetofleader", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettotargetrighthand", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowhoeverattacked", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowhoeverbumped", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowhoevercalledforhelp", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowhoeverhealed", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowhoeverisholding", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET, FUNC_PASSAGE }, "settargettowhoeverisinpassage", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowhoeverwashit", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowideblahid", { 0 } },
    { 0, { FUNC_SET, SVAR_TARGET }, "settargettowideenemy", { 0 } },
    { 0, { FUNC_SET, SVAR_MAP }, "settilexy", { 0 } },
    { 0, { FUNC_SET }, "settime", { 0 } },
    { 0, { FUNC_SET, SVAR_TURNMODE }, "setturnmodetospin", { 0 } },
    { 0, { FUNC_SET, SVAR_TURNMODE }, "setturnmodetovelocity", { 0 } },
    { 0, { FUNC_SET, SVAR_TURNMODE }, "setturnmodetowatch", { 0 } },
    { 0, { FUNC_SET, SVAR_TURNMODE }, "setturnmodetowatchtarget", { 0 } },
    { 0, { FUNC_SET }, "setvolumenearestteammate", { 0 } },
    { 0, { FUNC_SET, SVAR_MAP }, "setwaterlevel", { 0 } },
    { 0, { FUNC_SET, SVAR_MAP }, "setweathertime", { 0 } },
    { 0, { FUNC_SET, SVAR_MAP }, "setxy", { 0 } },
    { 0, { 0 }, "showblipxy", { 0 } },
    { 0, { 0 }, "showmap", { 0 } },
    { 0, { 0 }, "showtimer", { 0 } },
    { 0, { 0 }, "showyouarehere", { 0 } },
    { 0, { 0 }, "sneak", { 0 } },
    { 0, { 0 }, "sparkleicon", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnattachedcharacter", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnattachedfacedparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnattachedholderparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnattachedparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnattachedsizedparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawncharacter", { 0 } },
    { 0, { FUNC_SPAWN }, "spawncharacterxyz", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnexactcharacterxyz", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnexactchaseparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnexactparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnexactparticleendspawn", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnparticle", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnpoof", { 0 } },
    { 0, { FUNC_SPAWN }, "spawnpoofspeedspacingdamage", { 0 } },
    { 0, { 0 }, "stop", { 0 } },
    { 0, { FUNC_SOUND }, "stopmusic", { 0 } },
    { 0, { FUNC_SOUND }, "stopsound", { 0 } },
    { 0, { FUNC_TARGET }, "stoptargetmovement", { 0 } },
    { 0, { FUNC_MIXED }, "takepicture", { 0 } },
    { 0, { FUNC_TARGET }, "targetdamageself", { 0 } },
    { 0, { FUNC_TARGET }, "targetdoaction", { 0 } },
    { 0, { FUNC_TARGET }, "targetdoactionsetframe", { 0 } },
    { 0, { FUNC_TEAM }, "targetjointeam", { 0 } },
    { 0, { FUNC_TARGET }, "targetpayforarmor", { 0 } },
    { 0, { FUNC_TELEPORT }, "teleport", { 0 } },
    { 0, { FUNC_TELEPORT }, "teleporttarget", { 0 } },
    { 0, { FUNC_ORDER }, "translateorder", { 0 } },
    { 0, { FUNC_SPELL }, "undoenchant", { 0 } },
    { 0, { 0 }, "unkeepaction", { 0 } },
    { 0, { 0 }, "unkursetarget", { 0 } },
    { 0, { 0 }, "unkursetargetinventory", { 0 } },
    { 0, { 0 }, "unsparkleicon", { 0 } },
    { 0, { 0 }, "walk", { 0 } },
    { 0, { 0 }, "", { 0 } },
};

static SCRIPT_CONST_T ScrConst[] = 
{
    { SVAR_BLAH,   1, "blahdead" },
    { SVAR_BLAH,   2, "blahenemies" },
    { SVAR_BLAH,   4, "blahfriends" },
    { SVAR_BLAH,   8, "blahitems" },
    { SVAR_BLAH,  16, "blahinvertid" },
    { SVAR_BLAH,  32, "blahplayers" },"
    { SVAR_BLAH,  64, "blahskill" },
    { SVAR_BLAH, 128, "blahquest" },
    { SVAR_STATE,   0, "stateparry" },
    { SVAR_STATE,   1, "statewander" },
    { SVAR_STATE,   2, "stateguard" },
    { SVAR_STATE,   3, "statefollow" },
    { SVAR_STATE,   4, "statesurround" },
    { SVAR_STATE,   5, "stateretreat" },
    { SVAR_STATE,   6, "statecharge" },
    { SVAR_STATE,   7, "statecombat" },
    { SVAR_GRIP,    4, "griponly" },
    { SVAR_GRIP,    4, "gripleft" },
    { SVAR_GRIP,    8, "gripright" },
    { SVAR_SPAWN,   0, "spawnorigin" },
    { SVAR_SPAWN,   1, "spawnlast" },
    { SVAR_LATCH,   1, "latchleft" },
    { SVAR_LATCH,   2, "latchright" },
    { SVAR_LATCH,   4, "latchjump" },
    { SVAR_LATCH,   8, "latchaltleft" },
    { SVAR_LATCH,  16, "latchaltright" },
    { SVAR_LATCH,  32, "latchpackleft" },
    { SVAR_LATCH,  64, "latchpackright" },
    { SVAR_DAMAGE,  0, "damageslash" },
    { SVAR_DAMAGE,  1, "damagecrush" },
    { SVAR_DAMAGE,  2, "damagepoke" },
    { SVAR_DAMAGE,  3, "damageholy" },
    { SVAR_DAMAGE,  4, "damageevil" },
    { SVAR_DAMAGE,  5, "damagefire" },
    { SVAR_DAMAGE,  6, "damageice" },
    { SVAR_DAMAGE,  7, "damagezap" },
    { SVAR_ACTION, 'DA', "actionda" },
    { SVAR_ACTION, 'DB', "actiondb" },
    { SVAR_ACTION, 'DC', "actiondc" },
    { SVAR_ACTION, 'DD', "actiondd" },
    { SVAR_ACTION, 'UA', "actionua" },
    { SVAR_ACTION, 'UB', "actionub" },
    { SVAR_ACTION, 'UC', "actionuc" },
    { SVAR_ACTION, 'UD', "actionud" },
    { SVAR_ACTION, 'TA', "actionta" },
    { SVAR_ACTION, 'TB', "actiontb" },
    { SVAR_ACTION, 'TC', "actiontc" },
    { SVAR_ACTION, 'TD', "actiontd" },
    { SVAR_ACTION, 'CA', "actionca" },
    { SVAR_ACTION, 'CB', "actioncb" },
    { SVAR_ACTION, 'CC', "actioncc" },
    { SVAR_ACTION, 'CD', "actioncd" },
    { SVAR_ACTION, 'SA', "actionsa" },
    { SVAR_ACTION, 'SB', "actionsb" },
    { SVAR_ACTION, 'SC', "actionsc" },
    { SVAR_ACTION, 'SD', "actionsd" },
    { SVAR_ACTION, 'BA', "actionba" },
    { SVAR_ACTION, 'BB', "actionbb" },
    { SVAR_ACTION, 'BC', "actionbc" },
    { SVAR_ACTION, 'BD', "actionbd" },
    { SVAR_ACTION, 'LA', "actionla" },
    { SVAR_ACTION, 'LB', "actionlb" },
    { SVAR_ACTION, 'LC', "actionlc" },
    { SVAR_ACTION, 'LD', "actionld" },
    { SVAR_ACTION, 'XA', "actionxa" },
    { SVAR_ACTION, 'XB', "actionxb" },
    { SVAR_ACTION, 'XC', "actionxc" },
    { SVAR_ACTION, 'XD', "actionxd" },
    { SVAR_ACTION, 'FA', "actionfa" },
    { SVAR_ACTION, 'FB', "actionfb" },
    { SVAR_ACTION, 'FC', "actionfc" },
    { SVAR_ACTION, 'FD', "actionfd" },
    { SVAR_ACTION, 'PA', "actionpa" },
    { SVAR_ACTION, 'PB', "actionpb" },
    { SVAR_ACTION, 'PC', "actionpc" },
    { SVAR_ACTION, 'PD', "actionpd" },
    { SVAR_ACTION, 'EA', "actionea" },
    { SVAR_ACTION, 'EB', "actioneb" },
    { SVAR_ACTION, 'RA', "actionra" },
    { SVAR_ACTION, 'ZA', "actionza" },
    { SVAR_ACTION, 'ZB', "actionzb" },
    { SVAR_ACTION, 'ZC', "actionzc" },
    { SVAR_ACTION, 'ZD', "actionzd" },
    { SVAR_ACTION, 'WA', "actionwa" },
    { SVAR_ACTION, 'WB', "actionwb" },
    { SVAR_ACTION, 'WC', "actionwc" },
    { SVAR_ACTION, 'WD', "actionwd" },
    { SVAR_ACTION, 'JA', "actionja" },
    { SVAR_ACTION, 'JB', "actionjb" },
    { SVAR_ACTION, 'JC', "actionjc" },
    { SVAR_ACTION, 'HA', "actionha" },
    { SVAR_ACTION, 'HB', "actionhb" },
    { SVAR_ACTION, 'HC', "actionhc" },
    { SVAR_ACTION, 'HD', "actionhd" },
    { SVAR_ACTION, 'KA', "actionka" },
    { SVAR_ACTION, 'KB', "actionkb" },
    { SVAR_ACTION, 'KC', "actionkc" },
    { SVAR_ACTION, 'KD', "actionkd" },
    { SVAR_ACTION, 'MA', "actionma" },
    { SVAR_ACTION, 'MB', "actionmb" },
    { SVAR_ACTION, 'MC', "actionmc" },
    { SVAR_ACTION, 'MD', "actionmd" },
    { SVAR_ACTION, 'ME', "actionme" },
    { SVAR_ACTION, 'MF', "actionmf" },
    { SVAR_ACTION, 'MG', "actionmg" },
    { SVAR_ACTION, 'MH', "actionmh" },
    { SVAR_ACTION, 'MI', "actionmi" },
    { SVAR_ACTION, 'MJ', "actionmj" },
    { SVAR_ACTION, 'MK', "actionmk" },
    { SVAR_ACTION, 'ML', "actionml" },
    { SVAR_ACTION, 'MM', "actionmm" },
    { SVAR_ACTION, 'MN', "actionmn" },
    { SVAR_EXP, 0, "expsecret" },
    { SVAR_EXP, 1, "expquest" },
    { SVAR_EXP, 2, "expdare" },
    { SVAR_EXP, 3, "expkill" },
    { SVAR_EXP, 4, "expmurder" },
    { SVAR_EXP, 5, "exprevenge" },
    { SVAR_EXP, 6, "expteamwork" },
    { SVAR_EXP, 7, "exproleplay" },
    { SVAR_MSG, 0, "messagedeath" },
    { SVAR_MSG, 1, "messagehate" },
    { SVAR_MSG, 2, "messageouch" },
    { SVAR_MSG, 3, "messagefrag" },
    { SVAR_MSG, 4, "messageaccident" },
    { SVAR_MSG, 5, "messagecostume" },
    { SVAR_ORDER, 0, "ordermove" },
    { SVAR_ORDER, 1, "orderattack" },
    { SVAR_ORDER, 2, "orderassist" },
    { SVAR_ORDER, 3, "orderstand" },
    { SVAR_ORDER, 4, "orderterrain" },
    { SVAR_COLXP, 0, "white" },
    { SVAR_COLXP, 1, "red" },
    { SVAR_COLXP, 2, "yellow" },
    { SVAR_COLXP, 3, "green" },
    { SVAR_COLXP, 4, "blue" },
    { SVAR_COLXP, 0, "purple" },
    { SVAR_FX,   1, "fxnoreflect" },
    { SVAR_FX,   2, "fxdrawreflect" },
    { SVAR_FX,   4, "fxanim" },
    { SVAR_FX,   8, "fxwater" },
    { SVAR_FX,  16, "fxbarrier" },
    { SVAR_FX,  32, "fximpass" },
    { SVAR_FX,  64, "fxdamage" },
    { SVAR_FX, 128, "fxslippy" },
    { SVAR_TEAM,  0, "teama" },
    { SVAR_TEAM,  1, "teamb" },
    { SVAR_TEAM,  2, "teamc" },
    { SVAR_TEAM,  3, "teamd" },
    { SVAR_TEAM,  4, "teame" },
    { SVAR_TEAM,  5, "teamf" },
    { SVAR_TEAM,  6, "teamg" },
    { SVAR_TEAM,  7, "teamh" },
    { SVAR_TEAM,  8, "teami" },
    { SVAR_TEAM,  9, "teamj" },
    { SVAR_TEAM, 10, "teamk" },
    { SVAR_TEAM, 11, "teaml" },
    { SVAR_TEAM, 12, "teamm" },
    { SVAR_TEAM, 13, "teamn" },
    { SVAR_TEAM, 14, "teamo" },
    { SVAR_TEAM, 15, "teamp" },
    { SVAR_TEAM, 16, "teamq" },
    { SVAR_TEAM, 17, "teamr" },
    { SVAR_TEAM, 18, "teams" },
    { SVAR_TEAM, 19, "teamt" },
    { SVAR_TEAM, 20, "teamu" },
    { SVAR_TEAM, 21, "teamv" },
    { SVAR_TEAM, 22, "teamw" },
    { SVAR_TEAM, 23, "teamx" },
    { SVAR_TEAM, 24, "teamy" },
    { SVAR_TEAM, 25, "teamz" },
    { SVAR_INVENT, 1, "inventory" },
    { SVAR_INVENT, 2, "left" },
    { SVAR_INVENT, 3, "right" },
    { SVAR_GAMEL, 0, "easy" },
    { SVAR_GAMEL, 1, "normal" },
    { SVAR_GAMEL, 2, "hard" },
    { 0, 0, "" }   
};

static SCRIPT_ARG_T ScrArgVal[] = 
{
    { { FUNC_DATE, 1 } , "dateday" }, 
    { { FUNC_DATE, 2 } , "datemonth" }, 
    { { FUNC_GAMEL, 4 } , "difficulty" },
    { { FUNC_GOTO, 1 } , "gotodistance" },
    { { FUNC_GOTO, 3 } , "gotox" },
    { { FUNC_GOTO, 4 } , "gotoy" },
    { { FUNC_LEADER, 1 } , "leaderdistance" },
    { { FUNC_LEADER, 2 } , "leaderturn" },
    { { FUNC_LEADER, 3 } , "leaderx" },
    { { FUNC_LEADER, 4 } , "leadery" },
    { { FUNC_OWNER, 1 } , "ownerdistance" },
    { { FUNC_OWNER, 2 } , "ownerturn" },
    { { FUNC_OWNER, 3 } , "ownerx" },
    { { FUNC_OWNER, 4 } , "ownery" },
    { { FUNC_OWNER, 5 } , "ownerturnto" },
    // @todo: Check if this functions need an argument
    { { FUNC_MIXED, 1 } , "passage" },
    { { FUNC_MIXED, 2 } , "rand" },
    // Self
    { { FUNC_SELF,  1 } , "selfaccel" },
    { { FUNC_SELF,  2 } , "selfaltitude" },
    { { FUNC_SELF,  3 } , "selfammo" },
    { { FUNC_SELF,  4 } , "selfattached" },
    { { FUNC_SELF,  5 } , "selfcontent" },
    { { FUNC_SELF,  6 } , "selfcounter" },
    { { FUNC_SELF,  7 } , "selfdex" },
    { { FUNC_SELF,  8 } , "selfhateid" },
    { { FUNC_SELF,  9 } , "selfid" },
    { { FUNC_SELF, 10 } , "selfindex" },
    { { FUNC_SELF, 11 } , "selfint" },
    { { FUNC_SELF, 12 } , "selflevel" },
    { { FUNC_SELF, 13 } , "selflife" },
    { { FUNC_SELF, 14 } , "selfmana" },
    { { FUNC_SELF, 15 } , "selfmanaflow" },
    { { FUNC_SELF, SVAR_MONEY } , "selfmoney" },
    { { FUNC_SELF, 17 } , "selfmorale" },
    { { FUNC_SELF, 18 } , "selforder" },
    { { FUNC_SELF, 19 } , "selfspawnx" },
    { { FUNC_SELF, 20 } , "selfspawny" },
    { { FUNC_SELF, 21 } , "selfstate" },
    { { FUNC_SELF, 22 } , "selfstr" },
    { { FUNC_SELF, 23 } , "selfturn" },
    { { FUNC_SELF, 24 } , "selfwis" },
    { { FUNC_SELF, 25 } , "selfx" },
    { { FUNC_SELF, 26 } , "selfy" },
    { { FUNC_SELF, 27 } , "selfz" },
    // More mixed functions
    { { FUNC_MIXED, 3 } , "spawndistance" },
    { { FUNC_MIXED, 4 } , "swingturn" },
    // Target values 
    { {FUNC_TARGET,  1 } , "targetaltitude" },
    { {FUNC_TARGET,  2 } , "targetammo" },
    { {FUNC_TARGET,  3 } , "targetarmor" },
    { {FUNC_TARGET,  4 } , "targetdex" },
    { {FUNC_TARGET,  5 } , "targetdistance" },
    { {FUNC_TARGET,  6 } , "targetexp" },
    { {FUNC_TARGET,  7 } , "targetint" },
    { {FUNC_TARGET,  8 } , "targetlevel" },
    { {FUNC_TARGET,  9 } , "targetlife" },
    { {FUNC_TARGET, 10 } , "targetmana" },
    { {FUNC_TARGET, 11 } , "targetmanaflow" },
    { {FUNC_TARGET, 12 } , "targetmaxlife" },
    { {FUNC_TARGET, SVAR_MONEY } , "targetmoney" },
    { {FUNC_TARGET, 14 } , "targetreloadtime" },
    { {FUNC_TARGET, 15 } , "targetspeedx" },
    { {FUNC_TARGET, 16 } , "targetspeedy" },
    { {FUNC_TARGET, 17 } , "targetspeedz" },
    { {FUNC_TARGET, 18 } , "targetstr" },
    { {FUNC_TARGET, 19 } , "targetteam" },
    { {FUNC_TARGET, 20 } , "targetturn" },
    { {FUNC_TARGET, 21 } , "targetturnfrom" },
    { {FUNC_TARGET, 22 } , "targetturnto" },
    { {FUNC_TARGET, 23 } , "targetwis" },
    { {FUNC_TARGET, 24 } , "targetx" },
    { {FUNC_TARGET, 25 } , "targety" },
    { {FUNC_TARGET, 26 } , "targetz" },
    // time
    { { FUNC_TIME, 1 } , "timehours" },
    { { FUNC_TIME, 2 } , "timeminutes" },
    { { FUNC_TIME, 3 } , "timeseconds" },
    // more mixed functions
    { { FUNC_MIXED, 4 } , "weight" },
    { { FUNC_MIXED, 5 } , "xydistance" },
    { { FUNC_MIXED, 6 } , "xyturnto" },
    { { 0, 0 } , "" }
};

// Arguments for functions
static SCRIPT_ARG_T ScrArgs[] = 
{
    { { FUNC_TMP, 0 } , "tmpx" },
    { { FUNC_TMP, 1 } , "tmpy" },
    { { FUNC_TMP, 2 } , "tmpdist" },
    { { FUNC_TMP, 2 } , "tmpdistance" },
    { { FUNC_TMP, 3 } , "tmpturn" },
    { { FUNC_TMP, 4 } , "tmpargument" },
    { { 0, 0 } , "" }
};

/*******************************************************************************
* CODE                                                                         *
*******************************************************************************/

/* ========================================================================== */
/* ============================= PUBLIC FUNCTION(S) ========================= */
/* ========================================================================== */

/*
 * Name:
 *     scriptLoad
 * Function:
 *     Loads a script from     { 0, { 0 }, "given file, returns the number of the script to be
 *         { 0, { 0 }, "given as argument for the function 'scriptRun()' 
 * Input:
 *     char_no:   Run script for this character
 *     script_no: Run script with this number
 *     why:       Why is the script     { 0, { 0 }, "called ? (Replaces 'alerts')  
 */
void scriptLoad(int char_no, int script_no, int why)
{
}

/*
 * Name:
 *     scriptRun
 * Function:
 *     Runs the script for     { 0, { 0 }, "given character
 * Input:
 *     char_no:   Run script for this character
 *     script_no: Run script with this number
 *     why:       Why is the script     { 0, { 0 }, "called ? (Replaces 'alerts')  
 */
void scriptRun(int char_no, int script_no, int why)
{
}