"""
    ObjBaker - Object Editor for Egoboo
    Copyright (C) 2009  Sean Baker

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""
import Tkinter
from Tooltip import *

class Main :
    def __init__(self) :
        self.root = Tkinter.Tk()
        self.load_images()
        self.create_ToolbarGeneral()
        self.root.mainloop()

    def load_images(self) :
        self.images = []
        self.images.append('.\Images\egoboo1.ico')
        self.images.append(Tkinter.PhotoImage(file='.\Images\document-new.GIF'))
        self.images.append(Tkinter.PhotoImage(file='.\Images\document-open.GIF'))
        self.images.append(Tkinter.PhotoImage(file='.\Images\document-save.GIF'))
        self.images.append(Tkinter.PhotoImage(file='.\Images\edit-copy'))
        self.images.append(Tkinter.PhotoImage(file='.\Images\edit-paste'))
        self.images.append(Tkinter.PhotoImage(file='.\Images\edit-cut'))
        self.images.append(Tkinter.PhotoImage(file='.\Images\edit-delete'))
                                
    def create_ToolbarGeneral(self) :
        GeneralToolbar = Tkinter.Frame(self.root, bd=3)
        GeneralToolbar.pack(side='top', anchor='w', fill='x')
        GeneralToolbar_New = Tkinter.Button(GeneralToolbar, command=self.window_sad, image=self.images[1])
        GeneralToolbar_New.pack(side='left')
        GeneralToolbar_New_Tooltip = ToolTip(GeneralToolbar_New, text='New Object', delay=1000)
        GeneralToolbar_Open = Tkinter.Button(GeneralToolbar, command=self.window_sad, image=self.images[2])
        GeneralToolbar_Open.pack(side='left')
        GeneralToolbar_Open_Tooltip = ToolTip(GeneralToolbar_Open, text='Open Object', delay=1000)

    class Object :
        def write(self) :
            datatxt =   "//Data.txt " + self.name + " \n\n\nGenerated by ObjBaker [" + self.timestamp + "]"
        self.name = 'New Object'
        self.EgoScript = ''
        self.timestamp = ''
        
    def create_StatusBar(self) :
        Statusbar = Tkinter.Frame(self.root, bd=3)
        Statusbar.pack(side='bottom', anchor='e', fill='x', height=20)

    def update_FileFocus(self, context) :
        self.root.title('ObjBaker' + context.name)
        
    def create_MainArea(self, context) :
        if context == 'EgoScript' :
            #Do summat
    
    def create_ToolbarSpecific(self, context) :
        if context == 'EgoScript' :
            #load EgoScript Toolbar
        elif context == 'Particle'
            #load Particle Toolbar
        elif context == ''
            #DO NOTHING

    def window_sad(self) :
        top = Tkinter.Toplevel(self.root)
        top.title=('Error')
        top.wm_iconbitmap()
        text = Tkinter.Label(top, text="This feature has not been implemented yet", justify='center')
        text.pack()
        b = Tkinter.Button(top, text="Sorry", command=top.destroy)
        b.pack(side='bottom')

if __name__ == "__main__" :
    App = Main()
